name: Diopside
logo_image: '/assets/img/diamond.png'
email: 'diopside@gmail.com'
slogan: 'Предложения складываются в абзацы – и вы наслаждетесь очередным бредошедевром.'
address: 'Котлас, Архангельская область, Россия'
