name: Diopside
logo_image: /assets/img/diamond.png
slogan: Предложения складываются в абзацы – и вы наслаждетесь очередным бредошедевром.
email: diopside.new@gmail.com
address: Котлас, Архангельская область, Россия
