name: Diopside
collections_dir: _data/

collections:
  features:
    output: true
    permalink: /:collection/:name
  blog:
    output: true
    permalink: /:collection/:slug
  authors:
    output: false

defaults:
  - scope:
      type: features
    values:
      layout: post
