backend:
  name: github
  repo: DRIMchanskySites/Diopside
  branch: master

media_folder: 'assets/uploads'

collections:
  - label: 'Сайт'
    name: 'general'
    files:
      - label: 'Общая информация'
        name: 'site'
        file: '_data/site.yml'
        fields:
          - { label: Name, name: name, widget: string }
          - { label: Логотип, name: logo_image, widget: image }
          - { label: Слоган, name: slogan, widget: string }
          - { label: Почта, name: email, widget: string }
          - { label: Адрес, name: address, widget: string }
  - label: 'Авторы'
    name: 'authors'
    folder: '_authors/'
    create: true
    editor:
      preview: false
    fields:
      - { label: 'Полное имя', name: 'name', widget: 'string' }
      - { label: 'Отображаемое имя', name: 'display_name', widget: 'string' }
      - { label: 'Position', name: 'position', widget: 'string' }
  - label: 'Блоки'
    name: blocks
    files:
      - label: 'Первый экран'
        name: 'first_screen'
        file: '_data/content/home.yml'
        fields:
          - label: Шапка
            name: header
            widget: object
            fields:
              - { label: Заголовок, name: title, widget: string }
              - { label: Подзаголовок, name: subtitle, widget: string }
              - { label: Кнопка, name: button, widget: string }
      - label: 'Футер'
        name: 'footer'
        file: '_data/content/footer.yml'
        fields:
          - label: Шапка
            name: header
            widget: object
            fields:
              - { label: Заголовок, name: title, widget: string }
              - { label: Подзаголовок, name: subtitle, widget: string }
              - { label: Кнопка, name: button, widget: string }
  - label: 'Особенности'
    name: features
    folder: '_data/_features'
    create: true
    fields:
      - { label: Картинка, name: image, widget: image }
      - { label: Заголовок, name: title, widget: string }
      - { label: Описание, name: description, widget: string }
      - { label: 'Текст', name: 'body', widget: 'markdown' }
  - label: 'Новости'
    name: news
    create: true
    folder: '_data/_blog'
    sort: 'date:desc'
    slug: '{{year}}-{{month}}-{{day}}-{{slug}}'
    fields:
      - { label: 'Layout', name: 'layout', widget: 'hidden', default: 'post' }
      - { label: 'Изображение', name: 'image', widget: 'image', required: true }
      - { label: 'Время публикации', name: 'date', widget: 'datetime', default }
      - {
          label: 'Заголовок',
          name: 'title',
          widget: 'string',
          tagname: 'h1',
          required: true,
        }
      - {
          label: 'Автор',
          name: 'author',
          widget: 'relation',
          collection: 'authors',
          displayFields: [display_name],
          searchFields: [display_name],
          reauired: true,
          valueField: 'name',
        }
      - { label: 'Описание', name: 'desc', widget: 'string', required: true }
      - { label: 'Ссылка', name: 'slug', widget: 'string', required: true }
      - { label: 'Body', name: 'body', widget: 'markdown', required: true }
