backend:
  name: github
  repo: DRIMchanskySites/Diopside
  branch: master

media_folder: 'assets/uploads'

collections:
  - label: 'Сайт'
    name: 'general'
    files:
      - label: 'Общая информация'
        name: 'site'
        file: '_data/site.yml'
        fields:
          - { label: Name, name: name, widget: string }
          - { label: Логотип, name: logo_image, widget: image }
          - { label: Слоган, name: slogan, widget: string }
          - { label: Почта, name: email, widget: string }
          - { label: Адрес, name: address, widget: string }
  - label: 'Блоки'
    name: blocks
    files:
      - label: 'Первый экран'
        name: 'first_screen'
        file: '_data/content/home.yml'
        fields:
          - label: Шапка
            name: header
            widget: object
            fields:
              - { label: Заголовок, name: title, widget: string }
              - { label: Подзаголовок, name: subtitle, widget: string }
              - { label: Кнопка, name: button, widget: string }
      - label: 'Футер'
        name: 'footer'
        file: '_data/content/footer.yml'
        fields:
          - label: Шапка
            name: header
            widget: object
            fields:
              - { label: Заголовок, name: title, widget: string }
              - { label: Подзаголовок, name: subtitle, widget: string }
              - { label: Кнопка, name: button, widget: string }
