backend:
  name: github
  repo: DRIMchanskySites/Diopside
  branch: master

media_folder: 'assets/uploads'

collections:
  - label: 'Сайт'
    name: 'general'
    files:
      - label: 'Общая информация'
        name: 'site'
        file: '_data/site.yml'
        fields:
          - { label: Name, name: name, widget: string }
          - { label: Логотип, name: logo_image, widget: image }
          - { label: Слоган, name: slogan, widget: string }
          - { label: Почта, name: email, widget: string }
          - { label: Адрес, name: address, widget: string }
  - label: 'Страницы'
    name: 'pages'
    files:
      - label: 'Главная'
        name: 'home'
        file: '_data/content/home.yml'
        fields:
          - label: Главный экран
            name: first
            widget: object
            collapsed: true
            fields:
              - { label: Заголовок, name: title, widget: string }
              - { label: Подзаголовок, name: subtitle, widget: string }
              - { label: Главная кнопка, name: button, widget: string }
